project_id = "isypstatsbyacnnfpukx"

[functions.send-contact-email]
verify_jwt = false

[functions.fetch-rss-news]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-rss]
verify_jwt = false