-- Odswiezenie kultur: Artiser.pl (20 pozycji) — scrape 2026-07-05
-- Wygenerowane: scripts/gen-cultures-sql.py
BEGIN;
-- 1) wylacz stare wpisy tego sklepu (odwracalne)
UPDATE cultures SET is_active=false, updated_at=now() WHERE shop='Artiser.pl';
-- 2) wstaw odswiezony katalog
INSERT INTO cultures (name, composition, application, temperature, type, shop, shop_url, product_url, price_label, price_numeric, is_active, last_checked) VALUES
  ('ML', 'Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis', 'Sery miękkie, twarogowe do smarowania, podpuszczkowe miękkie i półtwarde', '25-35°C', 'mezofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-ML/130', '15,04 zł', 15.04, true, '2026-07-05'),
  ('MLL', 'Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis', 'Sery świeże, miękkie, półtwarde (feta, cheddar, twarogi, robiola)', '25-35°C', 'mezofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-MLL/119', '15,04 zł', 15.04, true, '2026-07-05'),
  ('ML-O', 'Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis biovar. diacetylactis, Lactococcus lactis subsp. lactis, Leuconostoc mesenteroides, Leuconostoc pseudomesenteroides', 'Twarogi, masło, śmietana, sery kwasowe i podpuszczkowe (gouda, cheddar, ser koryciński), pleśniowe', '25-35°C', 'mezofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-ML-O-do-twarogu-i-nie-tylko/131', '15,04 zł', 15.04, true, '2026-07-05'),
  ('MLE', 'Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis biovar. diacetylactis, Lactococcus lactis subsp. lactis, Leuconostoc mesenteroides, Streptococcus thermophilus', 'Sery świeże, miękkie, półtwarde, szczególnie pleśniowe', '25-40°C', 'mezofilno-termofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-MLE/132', '15,04 zł', 15.04, true, '2026-07-05'),
  ('BTH', 'Lactobacillus delbrueckii subsp. bulgaricus, Streptococcus thermophilus, Lactobacillus helveticus', 'Sery twarde typu Grana Padano, Parmezan, Sbrinz, Piora, Graviera', '37-45°C', 'termofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-BTH-/120', '15,04 zł', 15.04, true, '2026-07-05'),
  ('BTMH', 'Lactobacillus delbrueckii subsp. bulgaricus, Streptococcus thermophilus, Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis, Lactobacillus helveticus', 'Sery twarde, półtwarde, szwajcarskie (Montasio, Beaufort, Emmentaler, Toma)', '30-45°C', 'mezofilno-termofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-BTMH-/121', '15,04 zł', 15.04, true, '2026-07-05'),
  ('CLC', 'Streptococcus thermophilus', 'Sery z masy parzonej (Mozzarella, Scamorza, Provolone, Caciocavallo) i dojrzewające', '37-45°C', 'termofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-CLC/126', '18,50 zł', 18.5, true, '2026-07-05'),
  ('CLCH', 'Streptococcus thermophilus, Lactobacillus helveticus', 'Sery twarde i długo dojrzewające', '37-45°C', 'termofilne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-CLCH-/127', '15,04 zł', 15.04, true, '2026-07-05'),
  ('F-YO', 'Lactobacillus delbrueckii subsp. bulgaricus, Streptococcus thermophilus', 'Jogurty gęste, zwykłe, pitne oraz sery świeże (np. Crescenza)', '42-45°C', 'jogurtowe', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-do-jogurtu-F-YO/128', '15,04 zł', 15.04, true, '2026-07-05'),
  ('KFF', 'Debaryomyces hansenii, Lactococcus lactis subsp. cremoris, Lactococcus lactis subsp. lactis biovar. diacetylactis, Lactococcus lactis subsp. lactis, Leuconostoc, Streptococcus thermophilus', 'Kefir i mleczne napoje fermentowane', '20-25°C', 'kefir', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Kultury-bakterii-do-kefiru-KFF/129', '15,04 zł', 15.04, true, '2026-07-05'),
  ('P-YO', 'Lactobacillus delbrueckii subsp. bulgaricus, Streptococcus thermophilus, Lactobacillus acidophilus, Bifidobacterium bifidum, Lactobacillus paracasei', 'Jogurty probiotyczne (gęste, pitne) oraz sery świeże', '42-45°C', 'probiotyczne', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/P-YO-kultury-bakterii-do-jogurtu-z-probiotykami-/222', '15,04 zł', 15.04, true, '2026-07-05'),
  ('Penicillium Candidum', 'Penicillium candidum', 'Camembert, Brie, Chaource, Coulommiers i inne sery z porostem białej pleśni', '20-25°C', 'pleśniowe', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Penicillium-Candidum/133', '15,04 zł', 15.04, true, '2026-07-05'),
  ('Penicillium Roqueforti', 'Penicillium roqueforti', 'Gorgonzola, Roquefort, Stilton i sery z niebieską pleśnią', '20-25°C', 'pleśniowe', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Penicillium-Roqueforti/134', '15,04 zł', 15.04, true, '2026-07-05'),
  ('Propionibacterium', 'Propionibacterium freudenreichii', 'Sery z dziurami/oczkowaniem, typu Ementaler, Masdamer', '20-24°C', 'propionowe', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Propionibacterium/141', '15,04 zł', 15.04, true, '2026-07-05'),
  ('Brevibacterium Linens', 'Brevibacterium linens', 'Sery maziowe: Taleggio, Morbier, Limburger, Munster, Reblochon', '15-20°C', 'aromatyzujące', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Bakterie-maziowe-Brevibacterium-Linens/118', '15,04 zł', 15.04, true, '2026-07-05'),
  ('Geotrichum Candidum', 'Geotrichum candidum', 'Camembert, Brie, St. Marcellin, Chèvre i sery z porostem pleśni', '20-25°C', 'pleśniowe', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Geotrichum-Candidum/145', '15,04 zł', 15.04, true, '2026-07-05'),
  ('ARTiVEG ME-30', 'Lactococcus lactis subsp. lactis, Lactococcus lactis subsp. cremoris', 'Wegańskie alternatywy: Camembert, Brie, Robiola, twarogi i serki do smarowania', '25-35°C', 'wege', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Weganskie-kultury-bakterii-ARTiVEG-ME-30-na-5l-/123', '12,20 zł', 12.2, true, '2026-07-05'),
  ('ARTiVEG TH-33', 'Lactobacillus helveticus, Streptococcus thermophilus, Lactobacillus delbrueckii subsp. bulgaricus', 'Wegańskie alternatywy: Parmezan, Grana i inne sery twarde', '37-45°C', 'wege', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Weganskie-kultury-bakterii-ARTiVEG-TH-33-na-5l-/124', '12,20 zł', 12.2, true, '2026-07-05'),
  ('ARTiVEG YO-9', 'Lactobacillus delbrueckii subsp. bulgaricus, Streptococcus thermophilus', 'Wegańskie jogurty (greckie, zwykłe, pitne) i napoje z mleka roślinnego', '42-45°C', 'wege', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Weganskie-kultury-do-jogurtu-ARTiVEG-YO-9-na-5l-/125', '12,20 zł', 12.2, true, '2026-07-05'),
  ('ARTiVEG YO PRO-12', 'Streptococcus thermophilus, Lactobacillus delbrueckii subsp. bulgaricus, Bifidobacterium lactis, Lactobacillus casei, Lactobacillus paracasei', 'Wegańskie jogurty greckie/pitne i napoje z mleka roślinnego', '42-45°C', 'wege', 'Artiser.pl', 'https://artiser.pl/', 'https://artiser.pl/pl/p/Weganskie-kultury-jogurtowe-ARTiVEG-YO-PRO-12-na-5l-/122', '12,20 zł', 12.2, true, '2026-07-05');
COMMIT;
