-- Odswiezenie kultur: GAP Poland (19 pozycji) — scrape 2026-07-05
BEGIN;
UPDATE cultures SET is_active=false, updated_at=now() WHERE shop='GAP Poland';
INSERT INTO cultures (name, composition, application, temperature, type, shop, shop_url, product_url, price_label, price_numeric, is_active, last_checked) VALUES
  ('Brevibacterium linens', 'Brevibacterium linens', 'Sery z czerwoną/pomarańczową mazią powierzchniową, lekko pikantne (sery smarowane)', '15-22°C', 'aromatyzujące', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Brevibacterium-linens-/22901952', '20,00 zł', 20.0, true, '2026-07-05'),
  ('EF LYO', 'Enterococcus faecium', 'Sery twarde, półtwarde, feta (kultura aromatyzująca)', '25-35°C', 'mezofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/EF-LYO-/22901956', '18,00 zł', 18.0, true, '2026-07-05'),
  ('HL 06 LYO', 'Lactococcus lactis ssp. lactis, Streptococcus thermophilus', 'Sery półtwarde prasowane (Edamski, Gouda, Zamojski, Podlaski, Morski, Maasdamer)', '25-40°C', 'mezofilno-termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/HL-06-LYO-/22901954', '18,00 zł', 18.0, true, '2026-07-05'),
  ('MP 62 LYO', 'Streptococcus thermophilus', 'Mozzarella, oscypek, kaszkawał, ser do pizzy, Scamorza, Provolone', '37-45°C', 'termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/MP-62-LYO-/22901958', '18,00 zł', 18.0, true, '2026-07-05'),
  ('PB LYO', 'Propionibacterium freudenreichii ssp. shermanii, Propionibacterium freudenreichii ssp. globosum', 'Sery dojrzewające typu szwajcarskiego (Emmentaler) i holenderskiego (Maasdamer) - oczka', '20-24°C', 'propionowe', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/PB-LYO-/22901957', '18,00 zł', 18.0, true, '2026-07-05'),
  ('Protective LYO', 'Lactobacillus rhamnosus, Lactobacillus plantarum', 'Kultura ochronna (bakteriocyny): sery świeże i dojrzewające, feta, napoje fermentowane', '20-30°C', 'ochronne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Protective-LYO-/22901943', '52,70 zł', 52.7, true, '2026-07-05'),
  ('SH LYO', 'Lactococcus lactis ssp. lactis, Lactococcus lactis ssp. lactis biovar diacetylactis, Streptococcus thermophilus', 'Sery półtwarde z nieregularnymi oczkami (Bałtycki, Tylżycki, Trapistów, Warmiński, Butterkäse)', '25-40°C', 'mezofilno-termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/SH-LYO-/22901955', '18,00 zł', 18.0, true, '2026-07-05'),
  ('SR 62 LYO', 'Streptococcus thermophilus', 'Mozzarella, ser do pizzy, sery z masy parzonej (pasta filata)', '37-45°C', 'termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/SR-62-LYO-/22902182', '85,90 zł', 85.9, true, '2026-07-05'),
  ('TW 31 LYO', 'Lactococcus lactis ssp. lactis, Lactococcus lactis ssp. cremoris, Lactococcus lactis ssp. lactis biovar diacetylactis, Leuconostoc spp.', 'Sery świeże i miękkie, napoje mleczne fermentowane, śmietana', '25-35°C', 'mezofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/TW-31-LYO-/22901901', '18,00 zł', 18.0, true, '2026-07-05'),
  ('Y 92 LYO', 'Streptococcus thermophilus, Lactobacillus delbrueckii ssp. lactis, Lactobacillus helveticus', 'Sery bardzo twarde bez oczek (Parmezan, Grana, Sbrinz, Pecorino, sery włoskie)', '37-45°C', 'termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Y-92-LYO-/22901945', '18,00 zł', 18.0, true, '2026-07-05'),
  ('YPB LYO', 'Streptococcus thermophilus, Lactobacillus delbrueckii ssp. lactis, Lactobacillus helveticus, Propionibacterium freudenreichii ssp. shermanii, Propionibacterium freudenreichii ssp. globosum', 'Sery twarde z dużymi oczkami (Emmentaler, Gruyère, Comté)', '37-45°C', 'termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/YPB-LYO-/22901949', '18,00 zł', 18.0, true, '2026-07-05'),
  ('Kefir 41 LYO', 'Lactococcus lactis ssp. lactis, Lactococcus lactis ssp. lactis biovar diacetylactis, Lactobacillus brevis, Leuconostoc, Saccharomyces cerevisiae', 'Napoje fermentowane typu kefir', '20-25°C', 'kefir', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Kefir-41-LYO-/22901896', '18,00 zł', 18.0, true, '2026-07-05'),
  ('PBat 91 LYO', 'Lactococcus lactis ssp. lactis, Lactococcus lactis ssp. cremoris, Lactococcus lactis ssp. lactis biovar diacetylactis, Leuconostoc mesenteroides ssp. cremoris', 'Sery świeże, śmietana, masło', '25-35°C', 'mezofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/PBat-91-LYO-/22901953', '95,00 zł', 95.0, true, '2026-07-05'),
  ('SM 02 LYO', 'Lactococcus lactis ssp. lactis, Streptococcus thermophilus, Lactococcus lactis ssp. lactis biovar diacetylactis, Lactococcus lactis ssp. cremoris', 'Śmietana, napoje fermentowane (maślanka)', '25-40°C', 'mezofilno-termofilne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/SM-02-LYO/22902158', '6,00 zł', 6.0, true, '2026-07-05'),
  ('VEGE C LYO', 'Streptococcus thermophilus, Lactobacillus delbrueckii ssp. bulgaricus', 'Fermentacja żywności i napojów roślinnych (jogurty roślinne)', '25-40°C', 'wege', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/VEGE-C-LYO/22902224', '30,00 zł', 30.0, true, '2026-07-05'),
  ('YO 56 LYO', 'Lactobacillus delbrueckii ssp. bulgaricus, Streptococcus thermophilus', 'Jogurty z krótkim i długim nastawem', '42-45°C', 'jogurtowe', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/YO-56-LYO-/22901897', '18,00 zł', 18.0, true, '2026-07-05'),
  ('YO-B1 LYO', 'Lactobacillus delbrueckii ssp. bulgaricus, Streptococcus thermophilus, Lactobacillus acidophilus, Bifidobacterium lactis', 'Jogurt, mleko fermentowane (probiotyczne)', '42-45°C', 'probiotyczne', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/YO-B1-LYO-/22902117', '14,85 zł', 14.85, true, '2026-07-05'),
  ('Penicillium roqueforti', 'Penicillium roqueforti', 'Sery z przerostem niebieskiej pleśni (Rokpol, Gorgonzola, Danablu, Stilton)', '20-25°C', 'pleśniowe', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Penicilium-roqueforti-/22901951', '23,00 zł', 23.0, true, '2026-07-05'),
  ('Penicillium candidum', 'Penicillium candidum', 'Sery z porostem białej pleśni (Camembert, Brie, Crescenza)', '20-25°C', 'pleśniowe', 'GAP Poland', 'https://sklep.gappoland.com/', 'https://sklep.gappoland.com/pl/p/Penicillium-candidum-/22901950', '18,00 zł', 18.0, true, '2026-07-05');
COMMIT;
